version: "3.9"

services:
  postgres:
    image: postgres
    container_name: "container_postgres_agiota"
    restart: always
    ports: 
      - 5432:5432
    environment:
      POSTGRES_USER: ${DB_USER_POSTGRES}
      POSTGRES_PASSWORD: ${DB_PASS_POSTGRES}
      POSTGRES_DB: ${DB_DATABASE_POSTGRES}
